### ISSUE TITLE
No such file or directory: coc-stylua-data/stylua

### ISSUE THREAD

**Issue by johhnry** [xiyaowong/coc-stylua#4]
Hi,

I just installed Coc on Neovim and when I open a `.lua` file I have the following issue:

```
[coc.nvim]: Uncaught exception: ENOENT: no such file or directory, open '/home/josephhenry/.config/coc/extensions/coc-stylua-data/stylua'
```

Then it displays a coc progress bar with "Downloading StyLua..." endlessly.

Can someone help me solve this?

Thanks!

I have the following versions:

```
vim version: NVIM v0.7.2                           
node version: v16.10.0                                                                         
coc.nvim version: 0.0.82-d8561387 2022-08-07 04:42:37 +0800
coc-stylua version: 0.0.11
```

**Comment by xiyaowong** [comment]
Because download stylua failed. You need to wait until the progress bar disappears

**Comment by johhnry** [comment]
Thanks for the answer!

After 12 minutes it did nothing ;)

How does it install StyLua? Is it possible to have a progress bar or a log to see the progress?

**Comment by xiyaowong** [comment]
try following steps
```shell
cd ~/.config/coc/extension
rm coc-stylua-data -rf
mkdir coc-stylua
```

**Comment by johhnry** [comment]
Thanks it worked!

What I did was:

```shell
$ cd ~/.config/coc/extensions
$ mkdir coc-stylua-data
```

Then started editing a `.lua` file and it downloaded it successfully. It's strange that it didn't create the folder...

**Comment by afreakk** [comment]
same issue here, new install caused error, fixed by manually making `coc-stylua-data` directory.
